apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-kube-lb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - image: 080196/hello-kube
          name: hello-kube
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kubia-loadbalancer
spec:
  selector:
    app: kubia
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
